/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MidMatchPairFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createTokenPair(address,address,address)": FunctionFragment;
    "getPair(address,address)": FunctionFragment;
    "owner()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createTokenPair",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createTokenPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;

  events: {};
}

export class MidMatchPairFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MidMatchPairFactoryInterface;

  functions: {
    createTokenPair(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createTokenPair(address,address,address)"(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  createTokenPair(
    token0: string,
    token1: string,
    uniswapPoolAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createTokenPair(address,address,address)"(
    token0: string,
    token1: string,
    uniswapPoolAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getPair(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getPair(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createTokenPair(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createTokenPair(address,address,address)"(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createTokenPair(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createTokenPair(address,address,address)"(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createTokenPair(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createTokenPair(address,address,address)"(
      token0: string,
      token1: string,
      uniswapPoolAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
